services:
  proxy1: &base
    image: datagutten/feig-py
    restart: always
    ports:
      - "${PROXY1}:10001:10001"
    volumes:
      - ./data:/app/data
    command: python proxy.py ${GATE1}

  proxy2:
    <<: *base
    ports:
      - "${PROXY2}:10001:10001"
    command: python proxy.py ${GATE2}

  gate-api:
    build:
      dockerfile: Dockerfile-api
    restart: always
    ports:
      - "5000:80"


  parse_data:
    <<: *base
    restart: no
    command: python parse_data.py data
    volumes:
      - ./data:/app/data
      - ./parsed_data:/app/parsed_data

  prometheus:
    image: prom/prometheus
    restart: unless-stopped

    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=750d
      - --web.enable-admin-api

    volumes:
      #- ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    environment:
      - TZ=Europe/Oslo

  people_count_openmetrics:
    <<: *base
    restart: no
    command: python people_count_openmetrics.py
    environment:
      METRICS_FOLDER: /app/metrics/people_count
    volumes:
      - ./parsed_data:/app/parsed_data
      - prometheus:/app/metrics

volumes:
  prometheus: